# 模块功能：默认菜单数据定义# 作者：帅妹妹丶.8297
# 创建日期?2026-05-12
# 说明：纯数据，不包含任何数据库依?
DEFAULT_MENUS = [
    # 首页 - 公开访问
    {
        "key": "dashboard",
        "menu_name": "数据看板",
        "parent_key": None,
        "order_num": 1,
        "path": "/",
        "component": "dashboard/index",
        "route_name": "home",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "home",
        "perms": None,
        "remark": "数据总览首页（公开）",
    },
    # 日志管理 - 公开访问
    {
        "key": "logs_dir",
        "menu_name": "日志管理",
        "parent_key": None,
        "order_num": 2,
        "path": "",
        "component": None,
        "menu_type": "M",
        "visible": "0",
        "status": "0",
        "icon": "log",
        "perms": None,
        "remark": "日志管理目录（公开）",
    },
    {
        "key": "logs_list",
        "menu_name": "日志列表",
        "parent_key": "logs_dir",
        "order_num": 1,
        "path": "/logs",
        "component": "logs/index",
        "route_name": "logs",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "file",
        "perms": None,
        "remark": "日志列表页面（公开）",
    },
    {
        "key": "logs_upload",
        "menu_name": "上传日志",
        "parent_key": "logs_dir",
        "order_num": 2,
        "path": "/logs/upload",
        "component": "logs/upload",
        "route_name": "logs-upload",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "upload",
        "perms": "upload",
        "remark": "上传日志页面（需登录）",
    },
    {
        "key": "logs_detail",
        "menu_name": "日志详情",
        "parent_key": "logs_dir",
        "order_num": 3,
        "path": "/logs/:id",
        "component": "logs/detail",
        "route_name": "log-detail",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "file-text",
        "perms": None,
        "remark": "日志详情页面（公开）",
    },
    # 出勤统计 - 公开访问
    {
        "key": "attendance",
        "menu_name": "出勤统计",
        "parent_key": None,
        "order_num": 3,
        "path": "/attendance",
        "component": "attendance/index",
        "route_name": "attendance",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "users",
        "perms": None,
        "remark": "出勤统计页面（公开）",
    },
    # 技能循环分析 ?- 公开访问
    {
        "key": "skill_analysis",
        "menu_name": "技能循环分析",
        "parent_key": None,
        "order_num": 4,
        "path": "/skill-analysis",
        "component": "skill/index",
        "route_name": "skill-analysis",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "activity",
        "perms": None,
        "remark": "技能循环分析页面（公开）",
    },
    # Build管理 - 公开访问
    {
        "key": "builds_dir",
        "menu_name": "Build管理",
        "parent_key": None,
        "order_num": 5,
        "path": "",
        "component": None,
        "menu_type": "M",
        "visible": "0",
        "status": "0",
        "icon": "code",
        "perms": None,
        "remark": "Build管理目录（公开）",
    },
    {
        "key": "builds_library",
        "menu_name": "配置图书",
        "parent_key": "builds_dir",
        "order_num": 1,
        "path": "/builds",
        "component": "builds/library",
        "route_name": "builds",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "book",
        "perms": None,
        "remark": "配置图书馆页面（公开）",
    },
    {
        "key": "builds_parse",
        "menu_name": "Build解析",
        "parent_key": "builds_dir",
        "order_num": 2,
        "path": "/build-parser",
        "component": "builds/parser",
        "route_name": "build-parser",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "code",
        "perms": None,
        "remark": "Build代码解析页面（公开?）",
    },
    # 系统管理 - 需管理员权限
    {
        "key": "system_dir",
        "menu_name": "系统管理",
        "parent_key": None,
        "order_num": 6,
        "path": "",
        "component": None,
        "menu_type": "M",
        "visible": "0",
        "status": "0",
        "icon": "settings",
        "perms": "manage_users",
        "remark": "系统管理目录（管理员）",
    },
    {
        "key": "settings",
        "menu_name": "系统设置",
        "parent_key": "system_dir",
        "order_num": 1,
        "path": "/settings",
        "component": "settings/index",
        "route_name": "settings",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "cog",
        "perms": "manage_users",
        "remark": "系统设置页面（管理员）",
    },
    {
        "key": "scoring_rules",
        "menu_name": "评分规则",
        "parent_key": "system_dir",
        "order_num": 2,
        "path": "/scoring-rules",
        "component": "settings/scoring",
        "route_name": "scoring-rules",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "award",
        "perms": "manage_users",
        "remark": "评分规则页面（管理员）",
    },
    {
        "key": "dictionary",
        "menu_name": "字典管理",
        "parent_key": "system_dir",
        "order_num": 3,
        "path": "/dictionary",
        "component": "system/dictionary",
        "route_name": "Dictionary",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "list",
        "perms": "manage_users",
        "remark": "字典管理页面（管理员）",
    },
    {
        "key": "professions",
        "menu_name": "职业管理",
        "parent_key": "system_dir",
        "order_num": 4,
        "path": "/professions",
        "component": "system/professions",
        "route_name": "professions",
        "menu_type": "C",
        "visible": "0",
        "status": "0",
        "icon": "users",
        "perms": "manage_users",
        "remark": "职业、精英特长、角色定位管理（管理员）",
    },
]
